### ISSUE TITLE
Dust can't be smelted in furnace

### ISSUE THREAD

**Issue by DoCharlcate** [noobanidus/grindr#5]

**Comment by noobanidus** [comment]
Only dusts that have the equivalent ore dictionary entry ingot can be smelted. Unless you are having an issue with iron dust or gold dust, then you most likely need to install a mod that provides the relevant ores and ingots.

**Comment by DoCharlcate** [comment]
Hiya, Sorry I should have said it was an issue with Iron dust. I think the problem with it is due to a conflict with the mystical worlds mod which also adds an iron dust. With both installed, the Grindr cannot differentiate between the 2 and starts putting them both out and it ends up that neither iron dust can be smelted.

**Comment by noobanidus** [comment]
Oh, that's really strange. I'll have to experiment -- I'm the developer of Mystical World as well and was running them together in a previous pack and didn't experience this. Not that I doubt you, probably I just didn't experiment enough.

**Comment by noobanidus** [comment]
Looks like the issue is with Mystical World not having a smelting recipe, which is probably my fault.
