### ISSUE TITLE
Grindstones don't accept ores in top slot with hoppers.

### ISSUE THREAD

**Issue by PortalInTime** [noobanidus/grindr#6]
I'm assuming hopper interaction was intentional - It accepted coal in the bottom slot perfectly fine.
I'm using grindr-1.15.2-0.0.1.0 for Minecraft 1.15.2.

**Comment by noobanidus** [comment]
I'll look into it, thanks

**Comment by noobanidus** [comment]
So, it definitely seems to be working on 1.14.4: ![](https://i.imgur.com/UE06OOs.gif)

I'm just porting some changes forwards and I'll test it on 1.15.2.

**Comment by noobanidus** [comment]
And with 1.15.2: 
![](https://i.imgur.com/BdOj7NB.gif)

Can I ask if you have a grindstone equipped?

**Comment by PortalInTime** [comment]
> Can I ask if you have a grindstone equipped?

Yep, I have a grindstone in it. After further testing, I found out it only happens when the hopper is put on the _side_ of the grinder! That was my issue before.

**Comment by noobanidus** [comment]
The input/output slots are exactly the same as a normal furnace, for the record. Glad you got it sorted!
