### ISSUE TITLE
Iron Ore Dust not smeltable in furnace

### ISSUE THREAD

**Issue by DoCharlcate** [noobanidus/grindr#7]
Hiya. Everything was working fine again after the last update but todays update things have stopped working again. 

I think this time it is a conflict with InstantUnify. When iron ore is placed in the grindr, it gives out a darker coloured iron ore dust (without Wawla it is hard to know what mod it comes from sorry), but as soon as it is placed into the inventory it turns into a lighter coloured Iron ore dust that cannot be smelted.

**Comment by noobanidus** [comment]
Without knowing which mods the dusts that you are trying to smelt are from, there isn't really anything I can do to help. Try F3+H to turn on advanced inventory tooltips, which will show you the registry name of the item.

If you are unable to smelt it, and it is indeed `grindr:iron_dust`, then that could be an issue.

Do you have any issues with instant unify disabled?

**Comment by DoCharlcate** [comment]
The unsmeltable (lighter coloured) iron dust is from mysticworld and the smeltable darker coloured dust is from Grindr. Indeed the issue seems to be with instant unify turning all the Grindr dust into mysticworld dust which can't be smelted after it goes through the grindr. Disabling instant unify solves the issue by allowing it to remain as Grindr dust.

**Comment by noobanidus** [comment]
Ah, I'll need to get a new release of Mystical World out. Until then, you should be able to use a data pack to create a smelting recipe for the iron/gold/etc dusts from Mystical World into the relevant ingots.

**Comment by noobanidus** [comment]
I'll open an issue in Mystical World for this.
