### ISSUE TITLE
Neptunium from Aquaculture 2 doesn't work.

### ISSUE THREAD

**Issue by mjlmjl888** [noobanidus/grindr#9]
You can't use Neptunium to make a Neptunium grinder even thought there is one.

**Comment by noobanidus** [comment]
I confess I actually never tested that. This could be an issue in my part, or it could be a tag issue on Aquaculture's part. Was this for 1.14.4 or 1.15.2?

**Comment by mjlmjl888** [comment]
1.15.2

**Comment by noobanidus** [comment]
Thanks!

**Comment by mjlmjl888** [comment]
No probs!

**Comment by noobanidus** [comment]
Okay, that's because the recipe is defaulting to look for neptunium ore. I'm not sure why I decided on ore instead of ingots for the grindstone types.

**Comment by noobanidus** [comment]
I'm changing this to look for the item tag rather than the ore tag, as it's purely the creation of the grindstone.
